/*
    ***** BEGIN LICENSE BLOCK *****
	
	Copyright (c) 2010  Zotero
						Center for History and New Media
						George Mason University, Fairfax, Virginia, USA
						http://zotero.org
	
	Zotero is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.
	
	Zotero is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU Affero General Public License for more details.
	
	You should have received a copy of the GNU Affero General Public License
	along with Zotero.  If not, see <http://www.gnu.org/licenses/>.
    
    ***** END LICENSE BLOCK *****
*/

#include "nsISupports.idl"

/**
 * The zoteroIntegrationInstaller interface corresponds to an installer for a Zotero integration
 * component.
 */
[scriptable, uuid(44c1996f-06d1-4327-a485-1ecdc3b35488)]
interface zoteroIntegrationInstaller : nsISupports
{
  /**
   * Runs the installer. Pass failSilently = true if installer should not display any alerts or
   * dialogs if it fails.
   */
  void run(in boolean failSilently);
};

///////////////////////////////////////////////////////////////////////////////
